spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://119.3.106.10:3306/wangk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 119.3.106.10:9300
  redis:
    database: 0
    host: 192.168.6.2
    port: 6379
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
server:
  port: 8083
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  header: Authorization
  #令牌前缀
  token-start-with: Bearer
  #使用最少88位的base64对令牌进行编码
  base64-secret: a
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000
  # RefreshToken过期时间(秒)
  refreshToken-expireTime: 604800

fdfs:
  connect-timeout: 5000
  http:
    anti_steal_token: true
    secret_key: FastDFS1234567890
  pool:
    max-total: 200
    max-total-per-key: 20
    max-wait-millis: 25000
  reqHost: 192.168.0.128
  reqPort: 80
  so-timeout: 3000
  thumbImage:
    height: 150
    width: 150
  trackerList: 192.168.0.128:22122

